### PR TITLE
Add tutorials to u.com

### PR DESCRIPTION
**Pull request by tbille**
# Summary

Add redirect of tutorials.ubuntu.com to ubuntu.com

# QA

It seems I have an issue with the QA script:
```bash
./qa-deploy staging sites/ubuntu.com.yaml latest

curl -I -H 'Host: ubuntu.com' http://127.0.0.1/

```

### CODE REVIEW

**Comment by jkfran** [comment]
Hey, @tbille I have been trying to write the right syntax for this because looks like now it is a bit different to define routes.

The thing is that even with the new syntax doesn't work correctly when we define more than one route, @nottrobin are you aware of this? Looks like this PR https://github.com/canonical-web-and-design/deployment-configs/pull/304 break this because for docs.ubuntu.com is also failing:
```
./qa-deploy staging sites/docs.ubuntu.com.yaml
```

**Comment by nottrobin** [comment]
This works for me: https://pastebin.canonical.com/p/cGMrNv9jpr/

Are you using the right version of microk8s?

**Comment by jkfran** [comment]
https://github.com/canonical-web-and-design/deployment-configs/pull/307

**Comment by nottrobin** [comment]
Is it expected that https://staging.ubuntu.com/tutorials would 404? What path can I test that will actually exist?

**Comment by nottrobin** [comment]
Never mind, I'll build my own image from https://github.com/canonical-web-and-design/ubuntu.com/pull/6385 and test that.

**Comment by tbille** [comment]
@nottrobin yees I forgot to mention in the PR that I didn't have an image.
The idea was to check that we had multiple pods that started for tutorials blog and the rest.

**Pull request merged**
